### ISSUE TITLE
Is this action obsolete?

### ISSUE THREAD

**Issue by gsuess** [ahmadnassri/action-workflow-queue#31]
I don't see how this does anything different than what [jobs.<job_id>.concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) does. But if there is any advantage of using this action over the the inbuilt concurrency control feature, it might be worth documenting it in the readme.

**Comment by joreetz-otto** [comment]
@gsuess 
[jobs.<job_id>.concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) will only hold a single item in queue.

> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled.

If you want to have a longer queue you cant use the concurrency feature

**Comment by ahmadnassri** [comment]
@joreetz-otto this is a good clarification, be good to add it to the readme 👍

**Comment by joreetz-otto** [comment]
> @joreetz-otto this is a good clarification, be good to add it to the readme 👍

I will open a PR later, maybe tomorrow
